/* Generated By:JavaCC: Do not edit this line. ConstraintParserConstants.java */
package sequencingConstraints.constraintParser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ConstraintParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPENBRACE = 5;
  /** RegularExpression Id. */
  int CLOSEBRACE = 6;
  /** RegularExpression Id. */
  int COMMA = 7;
  /** RegularExpression Id. */
  int ALWAYS = 8;
  /** RegularExpression Id. */
  int IL = 9;
  /** RegularExpression Id. */
  int IR = 10;
  /** RegularExpression Id. */
  int IN = 11;
  /** RegularExpression Id. */
  int GL = 12;
  /** RegularExpression Id. */
  int GR = 13;
  /** RegularExpression Id. */
  int GN = 14;
  /** RegularExpression Id. */
  int OPENPAREN = 15;
  /** RegularExpression Id. */
  int CLOSEPAREN = 16;
  /** RegularExpression Id. */
  int NOT = 17;
  /** RegularExpression Id. */
  int CONCAT = 18;
  /** RegularExpression Id. */
  int AND = 19;
  /** RegularExpression Id. */
  int OR = 20;
  /** RegularExpression Id. */
  int IDENTIFIER = 21;
  /** RegularExpression Id. */
  int LETTER = 22;
  /** RegularExpression Id. */
  int DIGIT = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"_\"",
    "\"+-\"",
    "\"-+\"",
    "\"~\"",
    "\"+...\"",
    "\"...+\"",
    "\".~.\"",
    "\"(\"",
    "\")\"",
    "\"!\"",
    "\".\"",
    "\"&&\"",
    "\"||\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
  };

}
